FROM python:3.7

WORKDIR /code

COPY requirements.txt .
COPY flask_server.py .
COPY streamgear_test.py .
RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org cryptography
RUN pip install -r requirements.txt
RUN mkdir /video
COPY streamgear_test.py .

ENTRYPOINT ["tail", "-f", "/dev/null"]